[versions]
apiModule = "1.0.1"

paperApi = "1.21-R0.1-SNAPSHOT"
craftEngine = "26.9.1"
placeholderApi = "2.11.6"

[libraries]
paperApi = { module = "io.papermc.paper:paper-api", version.ref = "paperApi" }
craftEngineCore = { module = "net.momirealms:craft-engine-core", version.ref = "craftEngine" }
craftEngineBukkit = { module = "net.momirealms:craft-engine-bukkit", version.ref = "craftEngine" }
placeholderApi = { module = "me.clip:placeholderapi", version.ref = "placeholderApi" }
